# Should the plugin print with DEBUG level.
debug: true

# Trigger configuration for bound-items
trigger:
  left-click:
    air: false
    block: false
  right-click:
    air: true
    block: true
  attack: false
  ignore:
    sprint: false
    sneak: true

after-trigger:
  use-item: true
  use-block: false
