name: ExampleUSS
version: '${project.version}'
main: fr.jamailun.examples.ExamplePlugin
api-version: '1.21'
author: jamailun
description: Demo plugin for USS.

depend: [UltimateSpellSystem]
softdepend: [Citizens]

commands:
  spellcaster:
    description: cast a spell on a citizen NPC
    permission: uss.spellcaster
  tag.npc:
    description: Helper command to edit NPC (scoreboard) tags.
    permission: citizens2.tag

permissions:
  uss.spellcaster:
    default: op
