name: ExampleUSS
version: '${project.version}'
main: fr.jamailun.examples.ExamplePlugin
api-version: '1.21'
author: jamailun
description: test

depend: [UltimateSpellSystem]
softdepend: [Citizens]

commands:
  test-cast-npc:
    description: cast a spell on a citizen NPC
    permission: test-cast-npc

permissions:
  test-cast-npc:
    default: op
